// _mobile/main/src/router/Home.vue
<style lang="less" scoped>
	@import '../vars.less';
	.Home {
		font-size: 14px;
		.block {
			display: block;
			padding: 10px 15px;
			background: @green-bg;
			color: @green-text;
			//border-bottom: 1px solid @grey-border;
		}
	}
</style>

<template>
	<div class="Home">
		<div class="block">
			Greetings! I am a front-end developer.<br/>
			Github: github.com/403177368<br/>
			Website: madsoap.net<br/>
			Welcome, my friend! This is my personal website! Maybe you want to tap the navicon on top-left?
		</div>
	</div>
</template>

<script type="text/javascript">
	export default {
		
	}
</script>

// _mobile/main/src/deprecated/_home/Home.jsx
require('./Home.less');

class Home extends React.Component {
	render(){
		return (
			<div className="HOME">
				<div className="block">
					Greetings! I am a front-end developer.<br/>
					Github: github.com/403177368<br/>
					Website: madsoap.net<br/>
					Welcome, my friend! This is my personal website! Maybe you want to tap the navicon on top-left?
				</div>
			</div>
		)
	}
}

export {Home};
