// src/farm/src/components/Swiper.jsx
require('./Swiper.less');

class Swiper extends React.Component {
	constructor(props){
		super(props);
		var self = this;
		this.width = 0;
		this.Swiper = null;
		this.train = null;
		this.dots = null;
		this.$trainOffset = 0;
		this.$currentOne = 0;
		
		this.X0 = null;
		this.X1 = null;
		this.Y1 = null;
		this.Y2 = null;

		this.cycle = false;
		this.switching = false;
		this.moveCount = 0;
		this.canScroll = false;
		//console.log(this.props)

		this.state = {
			items: this.getNewItems(this.props.items),
			trainStyle: {
			},
			itemStyle: {
			},
			currentDot: 0
		}
	}
	componentDidMount(){
		//console.log(this.props)
		var self = this;
		this.train = this.refs.train;
		
		self.setWidth();
		window.addEventListener('resize',function(){
			self.setWidth();
		},50)
		if( this.props.autoplay===true ){
			setInterval( ()=>{
				if( this.cycle===false&&this.switching===false ){
					this.cycle = true;
					this.toNext();
				};
			},self.props.interval );
		};
		//console.log(this.$currentOne)
	}
	componentWillReceiveProps(newProps){
		this.$trainOffset = 0;
		this.$currentOne = 0;
		this.train.style.transition = '0s';
		this.train.style.webkitTransition = '0s';
		this.train.style.transform = 'translate3d(0,0,0)';
		this.train.style.webkitTransform = 'translate3d(0,0,0)';
		this.setState({
			items: this.getNewItems(newProps.items)
		})
	}
	getNewItems(items){
		var newItems = JSON.parse( JSON.stringify(items) );
		newItems.forEach((a,i)=>{
			a._id = i;
		})
		return newItems;
	}
	getCurrentDot(self){
		if( self.$currentOne>self.props.items.length-1 ){
			return self.$currentOne - self.props.items.length;
		}else{
			return self.$currentOne;
		}
	}
	setWidth(){
		var self = this;
		var swiper = self.refs.Swiper;
		self.width = Number( document.defaultView.getComputedStyle( swiper ).width.replace(/px/,'') );
		self.$trainOffset = -self.width*self.$currentOne;
		self.train.style.transition = '0s';
		self.train.style.webkitTransition = '0s';
		self.train.style.transform = 'translate3d('+self.$trainOffset+',0,0)';
		self.train.style.webkitTransform = 'translate3d('+self.$trainOffset+',0,0)';
	}
	updatePagi(){

	}
	toNext(){
		var self = this;
		if( !this.switching ){
			this.switching = true;
			if( self.$currentOne<self.state.items.length-1 ){
				self.$currentOne++;
				self.$trainOffset = -self.$currentOne*self.width;
			}else{
				if( self.props.carousel ){
					self.$currentOne = 0;
					self.$trainOffset = -self.state.items.length*self.width;
				}else if( self.props.autoplay){
					self.$currentOne = 0;
					self.$trainOffset = 0;
				}else{
					self.$trainOffset = -self.$currentOne*self.width;
				}
			};
			self.setState({currentDot:self.$currentOne})
			self.train.style.transition = self.props.duration+'ms';
			self.train.style.webkitTransition = self.props.duration+'ms';
			self.train.style.transform = 'translate3d('+self.$trainOffset+'px,0,0)';
			self.train.style.webkitTransform = 'translate3d('+self.$trainOffset+'px,0,0)';
			setTimeout(()=>{
				self.train.style.transition = '0s';
				self.train.style.webkitTransition = '0s';
				if( self.props.carousel&&self.$currentOne===0 ){
					self.$trainOffset = 0;
					self.train.style.transform = 'translate3d(0,0,0)';
					self.train.style.webkitTransform = 'translate3d(0,0,0)';
				};
				this.switching = false;
				this.cycle = false;
			},self.props.duration)
		};
	}
	toPrev(){
		var self = this;
		if( !this.switching ){
			this.switching = true;
			if( self.$currentOne>0 ){
				self.$currentOne--;
				self.$trainOffset = -self.$currentOne*self.width;
			}else{
				if( self.props.carousel ){
					self.$currentOne = self.state.items.length-1;
					self.$trainOffset = self.width;
				}else{
					self.$trainOffset = 0;
				};
			};
			self.setState({currentDot:self.$currentOne})
			self.train.style.transition = self.props.duration+'ms';
			self.train.style.webkitTransition = self.props.duration+'ms';
			self.train.style.transform = 'translate3d('+self.$trainOffset+'px,0,0)';
			self.train.style.webkitTransform = 'translate3d('+self.$trainOffset+'px,0,0)';
			setTimeout(()=>{
				self.train.style.transition = '0s';
				self.train.style.webkitTransition = '0s';
				if( self.props.carousel&&self.$currentOne===self.state.items.length-1 ){
					self.$trainOffset = -(self.state.items.length-1)*self.width;
					self.train.style.transform = 'translate3d('+self.$trainOffset+'px,0,0)';
					self.train.style.webkitTransform = 'translate3d('+self.$trainOffset+'px,0,0)';
				};
				this.switching = false;
				this.cycle = false;
			},self.props.duration)
		};
	}
	toItem(i){
		var self = this;
		if( !this.switching ){
			this.switching = true;
			this.$currentOne = i;
			this.$trainOffset = -i*this.width;
			self.setState({currentDot:self.$currentOne})
			self.train.style.transition = self.props.duration+'ms';
			self.train.style.webkitTransition = self.props.duration+'ms';
			self.train.style.transform = 'translate3d('+self.$trainOffset+'px,0,0)';
			self.train.style.webkitTransform = 'translate3d('+self.$trainOffset+'px,0,0)';
			setTimeout(()=>{
				self.train.style.transition = '0s';
				self.train.style.webkitTransition = '0s';
				this.switching = false;
				this.cycle = false;
			},self.props.duration)
		};
	}
	handleTouchStart(e){
		if( !this.cycle ){
			this.cycle = true;
			this.canScroll = false;
			this.moveCount = 0;
			this.X0 = this.X1 = e.changedTouches[0].pageX;
			this.Y1 = e.changedTouches[0].pageY;
		}
	}
	handleTouchMove(e){
		if( this.cycle&&!this.switching ){
			this.moveCount++;
			if( !this.canScroll ){
				if( this.moveCount===1 ){
					this.X2 = e.changedTouches[0].pageX;
					this.Y2 = e.changedTouches[0].pageY;
					var distanceY = this.Y2 - this.Y1;
					var distanceX = this.X2 - this.X1;
					if( Math.abs(distanceY)>Math.abs(distanceX) ){
						this.canScroll = true;
					}else{
						e.preventDefault();
					}
				}
				
				if( !this.canScroll&&this.props.sticky ){
					this.X2 = e.changedTouches[0].pageX;
					var distance = this.X2 - this.X1;
					this.$trainOffset += distance;
					this.train.style.transition = '0s';
					this.train.style.webkitTransition = '0s';
					this.train.style.transform = 'translate3d('+this.$trainOffset+'px,0,0)';
					this.train.style.webkitTransform = 'translate3d('+this.$trainOffset+'px,0,0)';
					this.X1 = this.X2;
				};
			};
		};
	}
	handleTouchEnd(e){
		if( this.cycle ){
			if( !this.canScroll ){
				this.X2 = e.changedTouches[0].pageX;
				var distance = this.X2 - this.X0;
				if( distance>0 ){
					this.toPrev();
				}else if( distance<0 ){
					this.toNext();
				}else{
					this.switching = false;
					this.cycle = false;
				}
			}else{
				this.switching = false;
				this.cycle = false;
			}
		};
	}
	render(){
		var self = this;
		var items = this.state.items;
		return (
			<div className="Swiper" ref="Swiper"
				style={this.props.style}
				onTouchStart={this.handleTouchStart.bind(this)}
				onTouchMove={this.handleTouchMove.bind(this)}
				onTouchEnd={this.handleTouchEnd.bind(this)}>
				<ul className="train"
				style={{marginLeft:self.props.carousel?'-100%':'0'}}
				ref="train">
					{this.props.carousel&&items.length>0?
						<a className="item" style={{
							backgroundImage: items[items.length-1].background?`url(${items[items.length-1].background})`:''
						}}></a>:null
					}
					{items.map(function(a,i){
						return(
							<a className="item" href={a.href||'#/shopping_cart'} key={i} style={{
								backgroundImage: a.background?`url(${a.background})`:''
							}}>
								{a.img?<img src={a.img}/>:null}
							</a>
						)
					})}
					{this.props.carousel&&items.length>0?
					<a className="item" style={{
						backgroundImage: items[0].background?`url(${items[0].background})`:''
					}}></a>:null}
				</ul>
				<div className="pagi">
					<ul className="pagination" ref="pagination">
						{this.props.pagi?this.props.items.map(function(elem,i){
							return(
								<li className={i===self.state.currentDot?'dot active':'dot'}
								onClick={self.toItem.bind(self,i)}>
								</li>
							)
						}):null}
					</ul>
				</div>
			</div>
		)
	}
}

Swiper.defaultProps = {
	items: [],
	duration: 300,
	interval: 3000,
	carousel: true,
	sticky: true,
	autoplay: true,
	pagi: true
}

export {Swiper};

// _mobile/vue/src/components/swiper.vue
<template>
<div class="swiper" 
	:style="style"
	v-on:touchstart="touchstart($event)"
	v-on:touchmove="touchmove($event)"
	v-on:touchend="touchend($event)">
	<ul class="train" 
		:style=" 'transform:translate3d('+trainOffsetX+'px,0,0);transition:'+transition+';' ">
		<li :class=" 'item '+(i===currentOne?'active':'') " 
			v-for="(item,i) in copy"
			:key="item.background" 
			:style=" `background:${item.background}` "></li>
	</ul>
</div>
</template>

<style lang="less" scoped>
.swiper {
	position: relative;
	width: 50%; height: 20vw;
	background: grey;
	margin: auto;
	.train {
		width: 1000%;
		height: 100%;
		.item {
			float: left;
			width: 10%; height: 100%;
			transform: scale(0.8);
			opacity: 0.6;
			transition: 0.5s;
		}
		.item.active {
			transform: scale(1);
			opacity: 1;
		}
	}
}
</style>

<script>
var swiper = {
	props: {
		items: {
			default: function(){
				return [];
			}
		},
		style: {},
		sticky: {
			default: true
		},
		autoplay: {
			default: false
		},
		duration: {
			default: 300
		},
		interval: {
			default: 500
		}
	},
	data: function(){
		return {
			width: 0,

			copy: [],

			switching: false,
			inCycle: false,
			moveCount: 0,
			scrolling: false,
			trainOffsetX: 0,
			X1: 0,
			X2: 0,

			currentOne: 2,
			transition: '0s',
			offset: 0
		}
	},
	computed: {
		transform: function(){
			return 'translate3d('+trainOffsetX+'px,0,0)';
		}
	},
	watch: {
		items: function(){
			this.copy = this.items;
		}
	},
	mounted: function(){
		this.copy = JSON.parse( JSON.stringify(this.items) );
		window.addEventListener('load',()=>{
			this.setWidth();
			this.trainOffsetX = -this.width*2;
		});
		window.addEventListener('resize',()=>{
			setTimeout(()=>{
				this.setWidth();
				this.trainOffsetX = -this.width*2;
			},50)
		})
		if( this.autoplay ){
			setInterval(()=>{
				this.toNext();
			},this.interval);
		}
	},
	methods: {
		setWidth: function(){
			this.transition = false;
			var elem = this.$el;
			var width = document.defaultView.getComputedStyle( elem ).width.replace(/px/,'');
			this.width = width;		
		},
		toNext: function(){
			if( this.currentOne<this.copy.length-1 ){
				this.currentOne++;
				this.transition = '0.3s';
				this.trainOffsetX = -this.width*3;
			}
			setTimeout(()=>{
				this.transition = '0s';
				var first = this.copy[0];
				this.copy.splice(0,1);
				this.copy.push(first);
				this.currentOne = 2;
				this.trainOffsetX = -this.width*2;
				this.switching = false;
			},this.duration);
		},
		toPrev: function(){
			if( this.currentOne>0 ){
				this.currentOne--;
				this.transition = '0.3s';
				this.trainOffsetX = -this.width;
			};
			setTimeout(()=>{
				this.transition = '0s';
				var zz = this.copy.length-1;
				var last = this.copy[zz];
				this.copy.splice(zz,1);
				this.copy.unshift(last);
				this.currentOne = 2;
				this.trainOffsetX = -this.width*2;
				this.switching = false;
			},this.duration)
		},
		touchstart: function(e){
			console.log(this.switching)
			if( this.switching===false ){
				this.inCycle = true;
				// reset states of this touch cycle
				this.moveCount = 0;
				this.scrolling = false;
				this.transition = '0s';
				
				this.X0 = this.X1 = e.changedTouches[0].pageX;
				this.Y1 = e.changedTouches[0].pageY;
			};
		},
		touchmove: function(e){
			if( this.inCycle&&!this.scrolling ){
				this.moveCount++;
				if( this.moveCount===1 ){
					this.X2 = e.changedTouches[0].pageX;
					this.Y2 = e.changedTouches[0].pageY;
					var distanceY = this.Y2 - this.Y1;
					var distanceX = this.X2 - this.X1;
					if( Math.abs(distanceY)>Math.abs(distanceX) ){
						this.scrolling = true;
					}
				}

				if( this.sticky ){
					this.X2 = e.changedTouches[0].pageX;
					var distance = this.X2-this.X1;
					this.X1 = this.X2;
					this.trainOffsetX += distance;
				}
			}
		},
		touchend: function(e){
			if( this.inCycle&&!this.scrolling ){
				this.X2 = e.changedTouches[0].pageX;
				var distance = this.X2-this.X0;
				if( distance<0 ){
					this.switching = true;
					this.toNext();
				}else if( distance>0 ){
					this.switching = true;
					this.toPrev();
				};
				this.inCycle = false;
			};
		}
	}
}
module.exports = swiper;
</script>
