// _mobile/farm/src/components/Swiper.jsx
require('./Swiper.less');

class Swiper extends React.Component {
	constructor(props){
		super(props);
		var self = this;

		this.$trainOffset = 0;
		this.$currentOne = this.props.items.length;
		
		this.X0 = null;
		this.X1 = null;
		this.Y0 = null;
		this.Y1 = null;

		this.cycle = false;
		this.switching = false;
		//console.log(this.props)

		this.state = {
			items: this.getNewItems(this.props.items),
			trainStyle: {
				marginLeft: `-${this.props.items.length}00%`
			},
			itemStyle: {
			},
			currentDot: 0
		}
	}
	componentDidMount(){
		//console.log(this.props)
		var self = this;
		//self.setWidth();
		window.addEventListener('resize',function(){
			//self.setWidth();
		})
		if( this.props.autoplay===true ){
			setInterval( ()=>{
				if( this.cycle===false&&this.switching===false ){
					this.cycle = true;
					this.toNext();
				};
			},self.props.interval );
		};
		this.$currentOne = this.props.items.length;
		//console.log(this.$currentOne)
	}
	componentWillReceiveProps(newProps){
		this.$trainOffset = 0;
		this.$currentOne = newProps.items.length;
		this.setState({
			items: this.getNewItems(newProps.items),
			trainStyle: {
				marginLeft: `-${newProps.items.length}00%`
			}
		})
	}
	getNewItems(items){
		var items1 = JSON.parse( JSON.stringify(items) );
		var items2 = JSON.parse( JSON.stringify(items) );
		var newItems = items1.concat(items2);
		newItems.forEach((a,i)=>{
			a._id = i;
		})
		return newItems;
	}
	getCurrentDot(self){
		if( self.$currentOne>self.props.items.length-1 ){
			return self.$currentOne - self.props.items.length;
		}else{
			return self.$currentOne;
		}
	}
	setWidth(){
		var self = this;
		var _Swiper = React.findDOMNode(self.refs.Swiper);
		self.$width = Number( document.defaultView.getComputedStyle( _Swiper ).width.replace(/px/,'') );
	}
	toNext(){
		var self = this;
		if(this.switching===false){
			this.switching = true;
			if( self.$currentOne<self.state.items.length-1 ){
				self.$currentOne++;
			}else{
				self.$currentOne = 0;
			};
			//console.log(self.$currentOne)
			this.setState({
				trainStyle: {
					marginLeft: `-${this.props.items.length}00%`,
					transition: `${this.props.duration/1000}s`,
					transform: 'translate3d(-5%,0,0)',
					webkitTransform: 'translate3d(-5%,0,0)'
				},
				currentDot: self.getCurrentDot(self)
			})
			setTimeout(()=>{
				var newItems = JSON.parse( JSON.stringify(this.state.items) );
				var a = newItems.splice(0,1)[0];
				newItems.push(a);
				//console.log(newItems)
				this.setState({
					items: newItems,
					trainStyle: {
						marginLeft: `-${this.props.items.length}00%`,
						transition: '0s',
						transform: 'translate3d(0,0,0)',
						webkitTransform: 'translate3d(0,0,0)'
					}
				})
				this.switching = false;
				this.cycle = false;
			},self.props.duration)
		};
	}
	toPrev(){
		var self = this;
		if(this.switching===false){
			this.switching = true;
			if( self.$currentOne>0 ){
				self.$currentOne--;
			}else{
				self.$currentOne = self.state.items.length-1;
			};
			this.setState({
				trainStyle: {
					marginLeft: `-${this.props.items.length}00%`,
					transition: `${this.props.duration/1000}s`,
					transform: 'translate3d(5%,0,0)',
					webkitTransform: 'translate3d(5%,0,0)'
				},
				currentDot: self.getCurrentDot(self)
			})
			setTimeout(()=>{
				var newItems = JSON.parse( JSON.stringify(this.state.items) );
				var a = newItems.splice(newItems.length-1,1)[0];
				newItems.unshift(a);
				//console.log(newItems)
				this.setState({
					items: newItems,
					trainStyle: {
						marginLeft: `-${this.props.items.length}00%`,
						transition: '0s',
						transform: 'translate3d(0,0,0)',
						webkitTransform: 'translate3d(0,0,0)'
					}
				})
				this.switching = false;
				this.cycle = false;
			},self.props.duration)
		};
	}
	handleTouchStart(e){
		if(this.cycle===false&&this.switching===false){
			this.cycle = true;
			this.X0 = this.X1 = e.changedTouches[0].pageX;
		}
	}
	handleTouchMove(e){
		if(this.cycle===true&&this.switching===false){
			if( this.props.sticky===true ){
				this.X2 = e.changedTouches[0].pageX;
				var distance = this.X2 - this.X1;
				this.$trainOffset += distance;
				this.X1 = this.X2;
				var trainStyle = {
					marginLeft: `-${this.props.items.length}00%`,
					transition: '0s',
					transform: 'translate3d('+this.$trainOffset+'px,0,0)',
					webkitTransform: 'translate3d('+this.$trainOffset+'px,0,0)'
				}
				this.setState({
					trainStyle: trainStyle
				})
			};
		};
	}
	handleTouchEnd(e){
		if(this.cycle===true&&this.switching===false){
			this.X2 = e.changedTouches[0].pageX;
			var distance = this.X2 - this.X0;
			//console.log(distance);
			this.$trainOffset = 0;
			if( distance>0 ){
				this.toPrev();
			}else if( distance<0 ){
				this.toNext();
			}else{

			}
		};
	}
	render(){
		var self = this;
		return (
			<div className="Swiper" ref="Swiper"
				style={this.props.style}
				onTouchStart={this.handleTouchStart.bind(this)}
				onTouchMove={this.handleTouchMove.bind(this)}
				onTouchEnd={this.handleTouchEnd.bind(this)}>
				<ul className="train" style={this.state.trainStyle}>
					{this.state.items.map(function(a,i){
						return(
							<a className="item" href={a.href||'#/'} key={i} style={{
								backgroundImage: a.background?`url(${a.background})`:''
							}}>
								{a.img?<img src={a.img}/>:null}
							</a>
						)
					})}
				</ul>
				<div className="pagi">
					<ul className="pagination" ref="pagination">
						{this.props.pagi?this.props.items.map(function(elem,i){
							return(
								<li className={i===self.state.currentDot?'dot active':'dot'}>
								</li>
							)
						}):null}
					</ul>
				</div>
			</div>
		)
	}
}

Swiper.defaultProps = {
	items: [],
	duration: 500,
	interval: 3000,
	sticky: true,
	autoplay: true,
	pagi: true
}

export {Swiper};

// _mobile/vue/src/components/swiper.vue
<template>
<div class="swiper" 
	:style="style"
	v-on:touchstart="touchstart($event)"
	v-on:touchmove="touchmove($event)"
	v-on:touchend="touchend($event)">
	<ul class="train" 
		:style=" 'transform:translate3d('+trainOffsetX+'px,0,0);transition:'+transition+';' ">
		<li :class=" 'item '+(i===currentOne?'active':'') " 
			v-for="(item,i) in copy"
			:key="item.background" 
			:style=" `background:${item.background}` "></li>
	</ul>
</div>
</template>

<style lang="less" scoped>
.swiper {
	position: relative;
	width: 50%; height: 20vw;
	background: grey;
	margin: auto;
	.train {
		width: 1000%;
		height: 100%;
		.item {
			float: left;
			width: 10%; height: 100%;
			transform: scale(0.8);
			opacity: 0.6;
			transition: 0.5s;
		}
		.item.active {
			transform: scale(1);
			opacity: 1;
		}
	}
}
</style>

<script>
var swiper = {
	props: {
		items: {
			default: function(){
				return [];
			}
		},
		style: {},
		sticky: {
			default: true
		},
		autoplay: {
			default: false
		},
		duration: {
			default: 300
		},
		interval: {
			default: 500
		}
	},
	data: function(){
		return {
			width: 0,

			copy: [],

			switching: false,
			inCycle: false,
			moveCount: 0,
			scrolling: false,
			trainOffsetX: 0,
			X1: 0,
			X2: 0,

			currentOne: 2,
			transition: '0s',
			offset: 0
		}
	},
	computed: {
		transform: function(){
			return 'translate3d('+trainOffsetX+'px,0,0)';
		}
	},
	watch: {
		items: function(){
			this.copy = this.items;
		}
	},
	mounted: function(){
		this.copy = JSON.parse( JSON.stringify(this.items) );
		window.addEventListener('load',()=>{
			this.setWidth();
			this.trainOffsetX = -this.width*2;
		});
		window.addEventListener('resize',()=>{
			setTimeout(()=>{
				this.setWidth();
				this.trainOffsetX = -this.width*2;
			},50)
		})
		if( this.autoplay ){
			setInterval(()=>{
				this.toNext();
			},this.interval);
		}
	},
	methods: {
		setWidth: function(){
			this.transition = false;
			var elem = this.$el;
			var width = document.defaultView.getComputedStyle( elem ).width.replace(/px/,'');
			this.width = width;		
		},
		toNext: function(){
			if( this.currentOne<this.copy.length-1 ){
				this.currentOne++;
				this.transition = '0.3s';
				this.trainOffsetX = -this.width*3;
			}
			setTimeout(()=>{
				this.transition = '0s';
				var first = this.copy[0];
				this.copy.splice(0,1);
				this.copy.push(first);
				this.currentOne = 2;
				this.trainOffsetX = -this.width*2;
				this.switching = false;
			},this.duration);
		},
		toPrev: function(){
			if( this.currentOne>0 ){
				this.currentOne--;
				this.transition = '0.3s';
				this.trainOffsetX = -this.width;
			};
			setTimeout(()=>{
				this.transition = '0s';
				var zz = this.copy.length-1;
				var last = this.copy[zz];
				this.copy.splice(zz,1);
				this.copy.unshift(last);
				this.currentOne = 2;
				this.trainOffsetX = -this.width*2;
				this.switching = false;
			},this.duration)
		},
		touchstart: function(e){
			console.log(this.switching)
			if( this.switching===false ){
				this.inCycle = true;
				// reset states of this touch cycle
				this.moveCount = 0;
				this.scrolling = false;
				this.transition = '0s';
				
				this.X0 = this.X1 = e.changedTouches[0].pageX;
				this.Y1 = e.changedTouches[0].pageY;
			};
		},
		touchmove: function(e){
			if( this.inCycle&&!this.scrolling ){
				this.moveCount++;
				if( this.moveCount===1 ){
					this.X2 = e.changedTouches[0].pageX;
					this.Y2 = e.changedTouches[0].pageY;
					var distanceY = this.Y2 - this.Y1;
					var distanceX = this.X2 - this.X1;
					if( Math.abs(distanceY)>Math.abs(distanceX) ){
						this.scrolling = true;
					}
				}

				if( this.sticky ){
					this.X2 = e.changedTouches[0].pageX;
					var distance = this.X2-this.X1;
					this.X1 = this.X2;
					this.trainOffsetX += distance;
				}
			}
		},
		touchend: function(e){
			if( this.inCycle&&!this.scrolling ){
				this.X2 = e.changedTouches[0].pageX;
				var distance = this.X2-this.X0;
				if( distance<0 ){
					this.switching = true;
					this.toNext();
				}else if( distance>0 ){
					this.switching = true;
					this.toPrev();
				};
				this.inCycle = false;
			};
		}
	}
}
module.exports = swiper;
</script>
